### ISSUE TITLE
iFrame & Embedded script resizing

### ISSUE THREAD

**Issue by proframework** [PaulSpr/jQuery-Equal-Height-Columns#1]
Great script - loving it. Especially love the feature to set a minWidth.

One problem I'm having is the loading of iFrames (I think).

For example, the WordPress plugin "ShareThis". Everything works perfectly until I include the Facebook Like button. Once the Like button is on the page, the script doesn't recognize the extra height set by the plugin, and the height comes up a little short. 

This same kind of thing also happened with a client embedding a script into her WordPress page that displayed a contact form. The script is called manually inside of the content (<script src="...) - the equal heights script doesn't seem to include the loaded script's height into the equation. I set it so the equal heights script is called on window load (jQuery(window).load(..... - but it made no difference.

Any ideas?

Thanks!

**Comment by PaulSpr** [comment]
I know what causes the problem. The plugin calculates height when the document's DOM is finished loading. It's possible that at that moment there are elements in the DOM that don't have their final height because their contents are not yet loaded. Images, videos and iframes driven by javascript might not be completely rendered yet.

You can easily check if thats the problem by resizing the browser after the content has been loaded. If the column heights are calculated correctly after the resize the above scenario is definitely the problem.

I fixed this for images in a recent update by attaching a loaded event to all images and firing of the calculations and resizing again. But it won't be a good solution to fix this for every edge case. But I have thought up a flexbile solution that would work something like this:

$('.blocks li').equalHeightColumns({
    'afterLoading' : 'iframe, .facebook',
    ''afterTimeout' : 1000
});

The afterLoading options takes elements within the original selector to which a load event attached. When that event fires, the column heights are re-calculated. This still won't solve the facebook like button problem, because the iframe is created after the DOM is loaded.

The afterTimeout option takes time in miliseconds and fires the recalculations again after the specified time.

I will update the plugin soon.

A short-term solution to the Facebook Like button problem is wrapping it in an element and setting a min-height on it.

Just out of interest, can I view the website the plugin is used on somewhere? I;d love to see how it's used in the wild ;)

**Comment by proframework** [comment]
Great ideas! Love it!

I'm integrating it into an option with my WordPress framework - I'm hoping to release the new version today. I'll hook you up with a couple links once I do so :)

Thanks!
Tom

**Comment by adbakke** [comment]
Experiencing same issue on a page I'm working on, works great otherwise! Tried a few other similar scripts, this one seems to work the best.

Thanks.

**Comment by PaulSpr** [comment]
I updated the plugin. It now has the 'afterLoading' and 'afterTimeout' options. You can also use them both (which was the trick that made my Facebook like box test work) at the same time. This tries to attach the 'afterLoading' event after the 'afterTimeout' timeout. This way dynamically added iframes will be found by the 'afterLoading' selector.

Hopefully this fixes your problems!

**Comment by proframework** [comment]
Hi Paul,

That fixed it! Perfect, thank you so much for the amazing script.

Tom
